export const SET_LOADING = "SET_LOADING"
export const MENUIMAGES = 'MENUIMAGES';
export const MENUITEMS ='MENUITEMS';
export const DELETE_MENU = 'DELETE_MENU';
export const GET_MENUITEMS_REQUESTED = 'GET_MENUITEMS_REQUESTED';
export const CREATE_MENUITEMS_REQUESTED = 'CREATE_MENUITEMS_REQUESTED';
export const DELETE_MENU_REQUESTED = 'DELETE_MENU_REQUESTED';
export const LOGGED_USER = 'LOGGED_USER';